URL_CBR=https://cbr.ru/scripts/XML_daily.asp
CONVERSION_HP_TO_KW=0.7355
CONVERSION_KW_TO_HP=1.36
BASE_RATE=20000
NEW_MULTIPLE=0.17
OLD_MULTIPLE=0.26
UTIL_FEE_HP_LIMIT=160
MIN_COST_TRANSFER=16
MAX_COST_TRANSFER=30
